import { ArrowLeft } from 'lucide-react';
import { useThemeStore } from '../store/themeStore';
import { Sun, Moon } from 'lucide-react';

type Props = {
  onBack: () => void;
};

export default function TermsOfService({ onBack }: Props) {
  const { mode, toggle } = useThemeStore();

  return (
    <div className="min-h-screen bg-[#07070d] text-white">
      {/* Ambient glows */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[10%] w-[500px] h-[500px] rounded-full bg-orange-500/[0.05] blur-[130px]" />
        <div className="absolute top-[20%] right-[-5%] w-[400px] h-[400px] rounded-full bg-sky-500/[0.05] blur-[120px]" />
      </div>

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between max-w-4xl mx-auto px-6 py-5 border-b border-white/[0.04]">
        <button
          onClick={onBack}
          className="inline-flex items-center gap-2 text-sm text-theme-muted hover:text-theme-primary transition-colors group"
        >
          <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-0.5" />
          Back to Home
        </button>
        <button
          onClick={toggle}
          className="w-9 h-9 flex items-center justify-center rounded-full border border-panel-border bg-panel hover:bg-panel-hover text-theme-dim hover:text-theme-primary transition-colors"
          title={mode === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          {mode === 'dark' ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
        </button>
      </nav>

      {/* Content */}
      <main className="relative z-10 max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-theme-muted mb-8">Last updated: July 2, 2026</p>

        <div className="prose prose-invert max-w-none space-y-8 text-theme-secondary">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing or using DreFlow ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, you must not use the Service.
            </p>
          </section>

          <section className="border border-amber-500/30 bg-amber-500/[0.04] rounded-xl p-6">
            <h2 className="text-xl font-bold text-amber-300 mb-4 uppercase tracking-wide">
              Warranty Disclaimer &amp; Limitation of Liability
            </h2>
            <p className="leading-relaxed font-medium">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS, DEVELOPERS, OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
              CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM,
              OUT OF, OR IN CONNECTION WITH THE SERVICE OR THE USE OR OTHER DEALINGS IN THE SERVICE.
            </p>
            <p className="leading-relaxed mt-4">
              The visual maps, cyclomatic complexity scores, and automated connection arrows generated by the
              Service are <strong>interpretive heuristics provided "AS IS"</strong>. DreFlow holds zero financial
              or legal liability for:
            </p>
            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>Downstream compilation errors resulting from interpretations of analyzed code</li>
              <li>Production database data corruption arising from schema visualizations or suggestions</li>
              <li>System misinterpretations of architectural relationships or code dependencies</li>
              <li>Any decisions made based on the interpretive output of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Intellectual Property Indemnity</h2>
            <p className="leading-relaxed">
              By using the Service, you represent and warrant that you:
            </p>
            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>
                <strong>Own or hold explicit authorization and/or licenses</strong> for any repository, schema file,
                source code, or code string you submit, upload, or analyze using the Service.
              </li>
              <li>
                Have the legal right to process and visualize any intellectual property you introduce to the platform.
              </li>
              <li>
                Agree to indemnify and hold harmless DreFlow, its developers, and affiliates from any claims,
                damages, or expenses (including reasonable attorney fees) arising from your use of third-party
                intellectual property without proper authorization.
              </li>
            </ul>
            <p className="leading-relaxed mt-3">
              Unauthorized use of copyrighted code, proprietary schemas, or trade secrets through this platform
              is strictly prohibited and constitutes a violation of these Terms.
            </p>
          </section>

          <section className="border border-sky-500/30 bg-sky-500/[0.04] rounded-xl p-6">
            <h2 className="text-xl font-semibold text-sky-300 mb-3">3. Children's Online Privacy (COPPA)</h2>
            <p className="leading-relaxed font-medium">
              DreFlow is strictly designed for and restricted to individuals aged <strong>13 years or older</strong>.
              The Service does not knowingly collect, use, or disclose personal information from children under 13
              years of age. If we become aware that we have inadvertently collected personal data from a child under 13,
              we will take immediate steps to delete such information.
            </p>
            <p className="leading-relaxed mt-3">
              By creating an account, you confirm that you are at least 13 years of age. Parents or guardians who
              believe their child has provided personal information to DreFlow should immediately contact us at
              <a href="mailto:privacy@dreflow.app" className="text-sky-400 hover:text-sky-300 ml-1">
                privacy@dreflow.app
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. User Conduct</h2>
            <p className="leading-relaxed">You agree not to:</p>
            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Submit code or content that infringes on third-party intellectual property rights</li>
              <li>Attempt to reverse-engineer, decompile, or disrupt the Service infrastructure</li>
              <li>Share your account credentials with unauthorized individuals</li>
              <li>Use automated tools to scrape or extract data from the Service at scale</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. User-Generated Content</h2>
            <p className="leading-relaxed">
              You retain full ownership of all content you create using the Service, including designs, diagrams,
              and visualizations. DreFlow does not claim any ownership or license over your work. You are solely
              responsible for ensuring your content complies with applicable laws and does not infringe on
              third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Service Availability</h2>
            <p className="leading-relaxed">
              DreFlow strives to maintain high availability but does not guarantee uninterrupted access. We reserve
              the right to modify, suspend, or discontinue any aspect of the Service at any time without prior notice.
              Scheduled maintenance will be communicated when possible.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Termination</h2>
            <p className="leading-relaxed">
              You may terminate your account at any time by contacting us. We reserve the right to suspend or
              terminate accounts that violate these Terms. Upon termination, your right to use the Service ceases
              immediately. Provisions that by their nature should survive termination will remain in effect.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Governing Law</h2>
            <p className="leading-relaxed">
              These Terms shall be governed by and construed in accordance with applicable law, without regard to
              conflict of law principles. Any disputes shall be resolved through binding arbitration in accordance
              with applicable arbitration rules.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p className="leading-relaxed">
              We may update these Terms from time to time. Material changes will be communicated via email or
              in-app notification. Continued use of the Service after changes constitutes acceptance of the
              revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Contact</h2>
            <p className="leading-relaxed">
              For questions about these Terms, contact us at:
              <a href="mailto:legal@dreflow.app" className="text-sky-400 hover:text-sky-300 ml-1">
                legal@dreflow.app
              </a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
